[package]
name = "dispute"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = { version = "21.5.0", features = ["testutils"] }
brain-storm-shared = { path = "../shared", default-features = false }

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
